### ISSUE TITLE
Unable to run formal verification.

### ISSUE THREAD

**Issue by teezzan** [RobertBaruch/nmigen-exercises#2]
Thank You for this awesome work.

I have been facing a little problem of Running the formal verification engine for covers. My code compiles without error but the formal verification is full of error such as

```bash

sby -f answers/e01_to_pennies.sby cover
SBY 18:04:31 [answers/e01_to_pennies_cover] Removing direcory 'answers/e01_to_pennies_cover'.
SBY 18:04:31 [answers/e01_to_pennies_cover] Copy 'toplevel.il' to 'answers/e01_to_pennies_cover/src/toplevel.il'.
SBY 18:04:31 [answers/e01_to_pennies_cover] engine_0: smtbmc z3
SBY 18:04:31 [answers/e01_to_pennies_cover] base: starting process "cd answers/e01_to_pennies_cover/src; yosys -ql ../model/design.log ../model/design.ys"
SBY 18:04:31 [answers/e01_to_pennies_cover] base: finished (returncode=0)
SBY 18:04:31 [answers/e01_to_pennies_cover] smt2: starting process "cd answers/e01_to_pennies_cover/model; yosys -ql design_smt2.log design_smt2.ys"
SBY 18:04:31 [answers/e01_to_pennies_cover] smt2: finished (returncode=0)
SBY 18:04:31 [answers/e01_to_pennies_cover] engine_0: starting process "cd answers/e01_to_pennies_cover; yosys-smtbmc -s z3 --presat -c --noprogress -t 1 --append 0 --dump-vcd engine_0/trace%.vcd --dump-vlogtb engine_0/trace%_tb.v --dump-smtc engine_0/trace%.smtc model/design_smt2.smt2"
SBY 18:04:32 [answers/e01_to_pennies_cover] engine_0: ##   0:00:00  Solver: z3
SBY 18:04:32 [answers/e01_to_pennies_cover] engine_0: Traceback (most recent call last):
SBY 18:04:32 [answers/e01_to_pennies_cover] engine_0: File "/usr/local/bin/yosys-smtbmc", line 398, in <module>
SBY 18:04:32 [answers/e01_to_pennies_cover] engine_0: smt.write(line)
SBY 18:04:32 [answers/e01_to_pennies_cover] engine_0: File "/usr/local/bin/../share/yosys/python3/smtio.py", line 359, in write
SBY 18:04:32 [answers/e01_to_pennies_cover] engine_0: self.setup()
SBY 18:04:32 [answers/e01_to_pennies_cover] engine_0: File "/usr/local/bin/../share/yosys/python3/smtio.py", line 213, in setup
SBY 18:04:32 [answers/e01_to_pennies_cover] engine_0: self.p_open()
SBY 18:04:32 [answers/e01_to_pennies_cover] engine_0: File "/usr/local/bin/../share/yosys/python3/smtio.py", line 307, in p_open
SBY 18:04:32 [answers/e01_to_pennies_cover] engine_0: self.p = subprocess.Popen(self.popen_vargs, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
SBY 18:04:32 [answers/e01_to_pennies_cover] engine_0: File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
SBY 18:04:32 [answers/e01_to_pennies_cover] engine_0: self._execute_child(args, executable, preexec_fn, close_fds,
SBY 18:04:32 [answers/e01_to_pennies_cover] engine_0: File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
SBY 18:04:32 [answers/e01_to_pennies_cover] engine_0: raise child_exception_type(errno_num, err_msg, err_filename)
SBY 18:04:32 [answers/e01_to_pennies_cover] engine_0: FileNotFoundError: [Errno 2] No such file or directory: 'z3'
SBY 18:04:32 [answers/e01_to_pennies_cover] engine_0: finished (returncode=1)
SBY 18:04:32 [answers/e01_to_pennies_cover] ERROR: engine_0: Engine terminated without status.
SBY 18:04:32 [answers/e01_to_pennies_cover] DONE (ERROR, rc=16)
```

What do you think is wrong?
I would also  love that you explain how the user's answer folder should be structured. This will help ease a lot of pain IMHO.

Thanks and Best Regards,
Taiwo

**Comment by teezzan** [comment]
After a little troubleshooting, It seems like Z3 isn't working at all on my device. I will keep looking.

**Comment by XekriRedmane** [comment]
Try using the docker image. It is set up properly for everything.
